// Generated by Wrangler on Wed Mar 06 2024 05:18:08 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	DB_DRIVER: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
}
