// Generated by Wrangler on Tue Jun 25 2024 15:07:18 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXTAUTH_SECRET: string;
	NEXTAUTH_URL: string;
	DB: D1Database;
}
